classmate = ['wy','dyz','zgz','mlt']
print(classmate)
a = len(classmate)
classmate.append(601)
print(classmate)
classmate.append([83018,'forgot',83123,83161])
print(classmate)
classmate.insert(5,2016)
print(classmate)
roommate = ('zgz','wy','dyz','murat')
print(roommate)